Update docker image
EGI-Federation/fedcloud-vmi-templates pull request #97
Opened 2024-09-13 06:32 UTC by enolfc

# Summary

---

**Related issue :**

2024-09-13 07:25 UTC, enolfc commented
Failing because the VM image for building is not found :(, will try to fix that and rebuild

2024-09-18 07:26 UTC, sebastian-luna-valero requested changes

2024-09-18 07:26 UTC, sebastian-luna-valero commented on ubuntu/appdb/docker.yaml
> +  sha512: "9e19ff5c80a646c173b94bfe7401a38ed7fc87b7617edfea9183cdfc9dc3e9ab51258170cf51fd807d3a20ebf7bf6faa151a8dcabfb4d44d66bebd7d29d0121d"
Could you please double check the checksum?

2024-09-18 10:42 UTC, enolfc commented
Everytime the image is built the checksum changes, so we cannot update both the yaml and the image in the same PR?

2024-09-18 10:59 UTC, merged

2024-09-18 10:59 UTC, enolfc commented
Forcing merge for now as the previous image expires today.
We need to have a better way of handling the shasum